# Generated by Django 5.1.6 on 2025-02-23 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 14, 1, 1, 378763, tzinfo=datetime.timezone.utc)),
        ),
    ]
