# Generated by Django 5.1.6 on 2025-02-23 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 14, 8, 39, 27842, tzinfo=datetime.timezone.utc)),
        ),
    ]
