# Generated by Django 5.1.6 on 2025-02-23 17:05

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_company_expiry_date_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 17, 5, 44, 132944, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='unique_id',
            field=models.IntegerField(blank=True, default=app.models.generate_unique_number, editable=False, max_length=4, null=True, unique=True),
        ),
    ]
