# Generated by Django 5.1.6 on 2025-02-23 17:15

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_company_expiry_date_alter_company_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 17, 15, 15, 200176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='unique_id',
            field=models.IntegerField(blank=True, default=app.models.generate_unique_number, editable=False, null=True, unique=True),
        ),
    ]
