# Generated by Django 5.1.6 on 2025-02-23 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_company_expiry_date_alter_company_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 17, 50, 55, 224753, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
