# Generated by Django 5.1.6 on 2025-02-23 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_company_expiry_date_alter_worker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 20, 10, 17, 515675, tzinfo=datetime.timezone.utc)),
        ),
    ]
