# Generated by Django 5.1.6 on 2025-02-26 20:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_company_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 20, 8, 22, 53608, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='progressitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
