# Generated by Django 5.1.6 on 2025-02-27 18:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_company_expiry_date_alter_progressitem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateforProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 18, 12, 27, 352935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Progresstype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='app.dateforprogress')),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='app.progresstype'),
        ),
    ]
