# Generated by Django 5.1.6 on 2025-02-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dateforprogress_alter_company_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 18, 20, 13, 844282, tzinfo=datetime.timezone.utc)),
        ),
    ]
