# Generated by Django 5.1.6 on 2025-02-27 18:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_company_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateforprogress',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 18, 52, 39, 537154, tzinfo=datetime.timezone.utc)),
        ),
    ]
