# Generated by Django 5.1.6 on 2025-02-27 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_dateforprogress_company_alter_company_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 18, 52, 57, 175352, tzinfo=datetime.timezone.utc)),
        ),
    ]
