# Generated by Django 5.1.6 on 2025-02-27 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_company_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 21, 0, 29, 304482, tzinfo=datetime.timezone.utc)),
        ),
    ]
