# Generated by Django 5.1.6 on 2025-03-01 20:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_company_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='type',
        ),
        migrations.AddField(
            model_name='work',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.progresstype'),
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 20, 32, 36, 875723, tzinfo=datetime.timezone.utc)),
        ),
    ]
