# Generated by Django 5.1.6 on 2025-03-05 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_progress_is_active_alter_company_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 14, 55, 47, 707769, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='progress',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
