# Generated by Django 5.1.6 on 2025-03-05 22:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_company_expiry_date_alter_progress_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence_date',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dateforprogress'),
        ),
        migrations.AddField(
            model_name='attendence_date',
            name='is_attend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 22, 29, 48, 794291, tzinfo=datetime.timezone.utc)),
        ),
    ]
