# Generated by Django 5.1.6 on 2025-03-05 22:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_attendence_date_date_attendence_date_is_attend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence_date',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dateforprogress'),
        ),
        migrations.AlterField(
            model_name='attendence_date',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 22, 34, 18, 507754, tzinfo=datetime.timezone.utc)),
        ),
    ]
