# Generated by Django 5.1.6 on 2025-03-06 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_attendence_date_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 19, 33, 56, 726736, tzinfo=datetime.timezone.utc)),
        ),
    ]
