# Generated by Django 5.1.6 on 2025-03-06 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_company_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence_date',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 20, 0, 26, 24409, tzinfo=datetime.timezone.utc)),
        ),
    ]
