# Generated by Django 5.1.6 on 2025-03-09 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_avans_number_alter_company_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 23, 4, 31, 820016, tzinfo=datetime.timezone.utc)),
        ),
    ]
