# Generated by Django 5.1.6 on 2025-03-10 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_company_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpanseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expanse_name', models.CharField(max_length=100)),
                ('expabse_type', models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim'), ('istisno', 'istisno')], default='istisno', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 16, 23, 37, 265429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Expanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('expanse_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.expansename')),
            ],
        ),
        migrations.DeleteModel(
            name='Expanses',
        ),
    ]
