# Generated by Django 5.1.6 on 2025-03-10 18:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_expansename_alter_company_expiry_date_expanse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansename',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 18, 39, 51, 441246, tzinfo=datetime.timezone.utc)),
        ),
    ]
