# Generated by Django 5.1.6 on 2025-03-10 19:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_expansename_company_alter_company_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 25, 19, 15, 1, 912814, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expanse',
            name='expanse_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.expansename'),
        ),
    ]
