# Generated by Django 5.1.6 on 2025-03-11 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_company_expiry_date_dateforexpanse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateforexpanse',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 22, 21, 14, 321464, tzinfo=datetime.timezone.utc)),
        ),
    ]
