# Generated by Django 5.1.6 on 2025-03-11 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_company_expiry_date_alter_dateforexpanse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 22, 45, 35, 720157, tzinfo=datetime.timezone.utc)),
        ),
    ]
